### PR TITLE
Update project file for Xcode 8/Swift 2.3

### PR DESCRIPTION
**Pull request by brendonjustin**

### CODE REVIEW

**Comment by KyleLeneau** [comment]
👍

**Comment by pennig** [comment]
If they're not necessary, can you omit the `"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "";` additions?

**Comment by brendonjustin** [comment]
Why? It isn't necessary, but Xcode recommends it.

**Comment by pennig** [comment]
I'm just paranoid about Xcode acting on our behalf when it comes to code signing.

**Comment by brendonjustin** [comment]
How's that?

**Comment by pennig** [comment]
paranoia assuaged 👍

**Pull request merged**
